export const REVIEW_DATA = {
    gamesPlayed: 2932,
    statsByMonth: {
        January: { overallRating: 1246, bulletRating: 1233, hoursPlayed: 12 },
        February: { rating: 1273, bulletRating: 1233, hoursPlayed: 17 },
        March: {
            rating: 1295,
            bulletRating: 1233,
            blitzRating: 1233,
            rapidRating: 1233,
            hoursPlayed: 14,
        },
        April: {
            rating: 1363,
            bulletRating: 1233,
            blitzRating: 1233,
            rapidRating: 1233,
            hoursPlayed: 19,
        },
        May: {
            rating: 1312,
            bulletRating: 1233,
            blitzRating: 1233,
            rapidRating: 1233,
            hoursPlayed: 22,
        },
        June: {
            rating: 1412,
            bulletRating: 1233,
            blitzRating: 1233,
            rapidRating: 1233,
            hoursPlayed: 31,
        },
        July: {
            rating: 1363,
            bulletRating: 1233,
            blitzRating: 1233,
            rapidRating: 1233,
            hoursPlayed: 7,
        },
        August: {
            rating: 1476,
            bulletRating: 1233,
            blitzRating: 1233,
            rapidRating: 1233,
            hoursPlayed: 2,
        },
        September: {
            rating: 1533,
            bulletRating: 1233,
            blitzRating: 1233,
            rapidRating: 1233,
            hoursPlayed: 12,
        },
        October: {
            rating: 1523,
            bulletRating: 1233,
            blitzRating: 1233,
            rapidRating: 1233,
            hoursPlayed: 22,
        },
        November: {
            rating: 1833,
            bulletRating: 1233,
            blitzRating: 1233,
            rapidRating: 1233,
            hoursPlayed: 32,
        },
        December: {
            rating: 1907,
            bulletRating: 1233,
            blitzRating: 1233,
            rapidRating: 1233,
            hoursPlayed: 15,
        },
    },
    hoursPlayed: 2356,
    highestAverageRating: 1734,
    rating: {
        rapid: [
            { month: 'January', rating: 1233 },
            { month: 'February', rating: 1276 },
            { month: 'March', rating: 1193 },
            { month: 'April', rating: 1293 },
            { month: 'May', rating: 1333 },
            { month: 'June', rating: 1467 },
            { month: 'July', rating: 1573 },
            { month: 'August', rating: 1671 },
            { month: 'September', rating: 1721 },
            { month: 'October', rating: 1662 },
            { month: 'November', rating: 1567 },
            { month: 'December', rating: 1729 },
        ],
        blitz: [
            { month: 'January', rating: 1233 },
            { month: 'February', rating: 1276 },
            { month: 'March', rating: 1193 },
            { month: 'April', rating: 1293 },
            { month: 'May', rating: 1333 },
            { month: 'June', rating: 1467 },
            { month: 'July', rating: 1573 },
            { month: 'August', rating: 1671 },
            { month: 'September', rating: 1721 },
            { month: 'October', rating: 1662 },
            { month: 'November', rating: 1567 },
            { month: 'December', rating: 1729 },
        ],
        bullet: [
            { month: 'January', rating: 1233 },
            { month: 'February', rating: 1276 },
            { month: 'March', rating: 1193 },
            { month: 'April', rating: 1293 },
            { month: 'May', rating: 1333 },
            { month: 'June', rating: 1467 },
            { month: 'July', rating: 1573 },
            { month: 'August', rating: 1671 },
            { month: 'September', rating: 1721 },
            { month: 'October', rating: 1662 },
            { month: 'November', rating: 1567 },
            { month: 'December', rating: 1729 },
        ],
    },
    ratingChange: 496,
    ratingChangePercent: 26.8,
    highestRatedOpponent: { name: 'Garrett Weng', rating: 2212 },
    lowestRatedOpponent: { name: 'Zach Jones', rating: 673 },
    biggestWin: { name: 'Braden Kelly', rating: 1734 },
    biggestLoss: { name: 'Jason Huang', rating: 832 },
    winPercent: 0.51,
    winPercentBullet: 0.52,
    winPercentBlitz: 0.54,
    winPercentRapid: 0.49,
    winPercentDaily: 0.71,
    percentWinWhite: 0.54,
    percentWinBlack: 0.46,
    percentDraw: 0.02,
    longestWinStreak: 13,
    longestLossStreak: 11,
    numBulletGames: 211,
    numBlitzGames: 134,
    numRapidGames: 77,
    numDailyGames: 7,
    highestRatingBullet: 1734,
    highestRatingBlitz: 1637,
    highestRatingRapid: 1729,
    highestDailyRating: 1433,
    mostPlayedOpenings: {
        white: [
            { name: 'Vienna Opening', count: 266 },
            { name: 'English Opening', count: 127 },
            { name: 'Scotch Gambit', count: 63 },
        ],
        black: [
            { name: 'Sicilian Defense', count: 253 },
            { name: 'French Defense', count: 133 },
            { name: 'Caro-Kann Defense', count: 47 },
        ],
    },
    mostPlayedOpponents: [
        { name: 'Braden Kelly', count: 12 },
        { name: 'Jason Huang', count: 9 },
        { name: 'Garrett Weng', count: 7 },
        { name: 'Zach Jones', count: 6 },
        { name: 'Ethan Li', count: 6 },
    ],
}
